### ISSUE TITLE
Add a background image to homepage

### ISSUE THREAD

**Issue by TimothyL96** [ITSocietyMMUMelaka/beta#1]
Background image missing, see screenshot below. Is it intended?
Anyway where to change background in this ... 'Hugo' ...?

![image](https://user-images.githubusercontent.com/16218167/32532129-07bad186-c483-11e7-83fd-582aafe724ab.png)

**Comment by garyng** [comment]
There is no background image in the first place. So it's not a bug.
Still working on other things though, so feel free to add any 😄

You can change the background image by modifying the file `site\layouts\index.html` and adding the appropriate css to `site\layouts\partials\head\site-custom.css`.
